export * from './cartItem.routes.js'
export * from './category.routes.js'
export * from './product.routes.js'
export * from './address.routes.js'
export * from './auth.routes.js'
export * from './orders.routes.js'
export * from './social-profiles.routes.js'
export * from './user.routes.js'
